# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_DRM_CIX) += cix-display.o
cix-display-objs := cix_display.o
obj-$(CONFIG_DRM_CIX_VIRTUAL) += cix_virtual.o
obj-$(CONFIG_DRM_LINLONDP) += linlon-dp/
obj-$(CONFIG_DRM_TRILIN_DPSUB) += dptx/
