# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_CIX_SKY1_SOCINFO)	+= sky1-socinfo.o
obj-$(CONFIG_CIX_DDR_LP)	+= cix-ddr-lp.o
obj-$(CONFIG_CIX_BUS_PERF)	+= cix-bus-perf.o
obj-$(CONFIG_CIX_ACPI_RESOURCE_LOOKUP)	+= cix-acpi-resource-lookup.o
obj-$(CONFIG_CIX_ACPI_USB_SCAN)		+= cix-acpi-usb-scan.o
obj-$(CONFIG_CIX_ACPI_GPU_SCAN)		+= cix-acpi-gpu-scan.o
